services:
  mongodb:
    image: mongo:7
    container_name: sebvm-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: sebvm
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fullstack-net

  server:
    build: ./server
    container_name: express-server
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGINS=https://sebvm.filldesigngroup.cloud,http://localhost:5173,http://localhost:5174,http://localhost:3000
      - MONGO_URI=mongodb://root:rootpass@mongodb:27017/sebvm?authSource=admin
      - JWT_SECRET=sebvm_9f3kL2pQ7xR8mN4vT6zA1wB5cD8yH0uJ
      - ADMIN_EMAIL=dev.filldesigngroup@gmail.com
      - ADMIN_PASSWORD=Testnet1@23!
    depends_on:
      - mongodb
    networks:
      - fullstack-net

  client:
    build: ./client
    container_name: react-client
    restart: unless-stopped
    ports:
      - "5174:3000"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - server
    networks:
      - fullstack-net

networks:
  fullstack-net:
    driver: bridge

volumes:
  mongo_data:
